Support filtering of employees based on status
officespacesoftware/api_client_powershell pull request #27
Opened 2020-07-02 17:41 UTC by gsanchezm179

Their documentation: https://developers.zenefits.com/docs/people
Either filter out all employees but the active ones or use a hash table to provide the list of desired statuses.

2020-07-02 20:23 UTC, ashsabet requested changes

2020-07-02 20:23 UTC, ashsabet commented on push_from_zenefits_to_officespace.ps1
> +            Write-Host "    (undesired employment status: $($u.status), skipping)"
@gsanchezm179 "undesired" has a very strong connotation.  Consider using the word "Filtered" instead.

2020-07-02 20:23 UTC, ashsabet commented on push_from_zenefits_to_officespace.ps1
> +            Write-Host "    (undesired employment status: $($u.status), skipping)"
Also, why "Write-Host" instead of using the log file?

2020-07-02 20:57 UTC, gsanchezm179 commented on push_from_zenefits_to_officespace.ps1
> +            Write-Host "    (undesired employment status: $($u.status), skipping)"
Updated the wording and replaced all instances of Write-Host with Write-Output to align with what we do in other scripts.

2020-07-15 20:10 UTC, ashsabet approved these changes

2020-07-15 20:10 UTC, merged